// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_lantern_configure_DeepState_TestHarness_generation.cpp and cpp_lantern_configure_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void cpp_lantern_configure(int log);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector log(1);
  log[0]  = RcppDeepState_int();
  qs::c_qsave(log,"/home/akhila/fuzzer_packages/fuzzedpackages/torch/inst/testfiles/cpp_lantern_configure/inputs/log.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "log values: "<< log << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_lantern_configure(log[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
